### PR TITLE
Use chart.interactiveLayer.tooltip.valueFormatter in lineChart [fixes #303]

### LINKED ISSUE #303: chart.interactiveLayer.tooltip.valueFormatter is ignored
I'm trying to use the valueFormatter with the cumulative line chart, but cannot get it to call the supplied function.

```
chart.interactiveLayer.tooltip
  // works as expected
  .headerFormatter(function(d) {
    console.log('headerFormatter called');
    return 'new header:'  + (new Date(d)).toDateString();
  })
  // doesn't work as expected
  .valueFormatter(function(d,i) {
    console.log('valueFormatter called');
    return 'Y U NO TIP?';
  })
```

example at: http://jsbin.com/urEkAYu/2/edit

Even though calling `chart.interactiveLayer.tooltip.valueFormatter()`, shows the new function, https://github.com/novus/nvd3/blob/development/src/tooltip.js#L104 is still using the [initial value for valueFormatter](https://github.com/novus/nvd3/blob/development/src/tooltip.js#L58)

### PR DESCRIPTION
**Pull request by apaatsio**
Fixes #303 for lineCharts.

### CODE REVIEW

File: src/models/lineChart.js [hunk 1]
```diff
@@ -410,11 +410,14 @@ nv.models.lineChart = function() {
...
+                    return d == null ? "N/A" : yAxis.tickFormat()(d);
+                };
+                var valueFormatter = interactiveLayer.tooltip.valueFormatter() ? interactiveLayer.tooltip.valueFormatter() : defaultValueFormatter;
+
                 interactiveLayer.tooltip
                     .chartContainer(chart.container.parentNode)
-                    .valueFormatter(function(d,i) {
-                        return d === null ? "N/A" : yAxis.tickFormat()(d);
-                    })
+                    .valueFormatter(valueFormatter)
```
Comment (liquidpele) [inline src/models/lineChart.js]: You can just do this without line 416 there:

    .valueFormatter(interactiveLayer.tooltip.valueFormatter() || defaultValueFormatter);

Comment (apaatsio) [inline src/models/lineChart.js]: @liquidpele Yeah, it looks better that way. Changed it.

**Comment by liquidpele** [comment]
awesome, thanks!
